{{- if .Values.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zlog-collector.fullname" . }}-config
  labels:
    app: {{ template "zlog-collector.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  log-collector-url: {{ default "" .Values.zebrium.collectorUrl | b64enc | quote }}
  auth-token: {{ default "" .Values.zebrium.authToken | b64enc | quote }}
{{- end }}
