apiVersion: v1
name: zlog-collector
description: Zebrium log collector daemonset for Kubernetes.
version: 1.53.0
appVersion: 1.50.0
keywords:
- logs
- logging
- log-management
- agent
- events
- daemonset
- logger
home: https://www.zebrium.com
icon: https://www.zebrium.com/hubfs/logo2.png
sources:
- https://github.com/zebrium/helm-charts/tree/main/charts/zlog-collector
maintainers:
- name: b3arp
  email: braeden@zebrium.com