apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zebeat.fullname" . }}-configurations
  labels:
    {{- include "zebeat.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.metricbeatConfig }}
  {{ $path }}: |
  {{ $config | nindent 4}}
  {{- end -}}
