apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zebeat.fullname" . }}-tokens
  labels:
  {{- include "zebeat.labels" . | nindent 4 }}
data:
{{- range $path, $config := .Values.accessTokens }}
  {{ $path }}: |
  {{ $config | nindent 4}}
{{- end -}}